"""initial schema

Revision ID: 585f0d556cb8
Revises: 
Create Date: 2026-09-15 11:43:29.202594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585f0d556cb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MERGED', 'WARNED', 'SUSPENDED', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_merged_into_id', 'users', ['merged_into_id'], unique=False)
    op.create_table('account_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('winner_user_id', sa.UUID(), nullable=False),
    sa.Column('loser_user_id', sa.UUID(), nullable=False),
    sa.Column('verified_e164', sa.String(), nullable=False),
    sa.Column('initiating_challenge_id', sa.UUID(), nullable=True),
    sa.Column('moved_platform_identities', sa.Integer(), nullable=False),
    sa.Column('moved_phone_claims', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_merges_loser_user_id', 'account_merges', ['loser_user_id'], unique=False)
    op.create_index('ix_account_merges_winner_user_id', 'account_merges', ['winner_user_id'], unique=False)
    op.create_table('khatms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_type', sa.Enum('SURAH', 'QURAN_PAGE', 'QURAN_SURAH', 'SALAWAT', 'DUA', 'ZIYARAT', 'CUSTOM', name='khatmtemplatetype'), nullable=False),
    sa.Column('khatm_type', sa.Enum('COMMITMENT', 'OPEN', name='khatmtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='khatmstatus'), nullable=False),
    sa.Column('quran_edition_id', sa.String(length=64), nullable=True),
    sa.Column('surah_number', sa.SmallInteger(), nullable=True),
    sa.Column('repetition_target', sa.Integer(), nullable=True),
    sa.Column('public_slug', sa.String(length=100), nullable=True),
    sa.Column('niyyat', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_slug')
    )
    op.create_index('ix_khatms_creator_user_id', 'khatms', ['creator_user_id'], unique=False)
    op.create_index('ix_khatms_status', 'khatms', ['status'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('e164', sa.String(), nullable=False),
    sa.Column('purpose', sa.Enum('PHONE_VERIFICATION', 'PHONE_LOGIN', name='otppurpose'), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_challenges_e164', 'otp_challenges', ['e164'], unique=False)
    op.create_index('ix_otp_challenges_user_e164_purpose', 'otp_challenges', ['user_id', 'e164', 'purpose'], unique=False)
    op.create_table('pending_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority')
    )
    op.create_index('ix_pending_payments_authority', 'pending_payments', ['authority'], unique=False)
    op.create_table('phone_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('e164', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', 'REVOKED', name='phoneclaimstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phone_claims_e164', 'phone_claims', ['e164'], unique=False)
    op.create_index('ix_phone_claims_user_id', 'phone_claims', ['user_id'], unique=False)
    op.create_table('platform_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('TELEGRAM', 'BALE', name='platform'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'subject', name='uq_platform_identities_platform_subject')
    )
    op.create_index('ix_platform_identities_user_id', 'platform_identities', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('user_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREATOR', name='capabilitytype'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_capabilities_user_id', 'user_capabilities', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'BASIC', 'PRO', name='plantier'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), nullable=False),
    sa.Column('reminder_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('font_size', sa.Enum('NORMAL', 'LARGE', name='fontsize'), nullable=False),
    sa.Column('preferred_reciter', sa.String(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_toman', sa.Integer(), nullable=False),
    sa.Column('credit_toman', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('khatm_allocation_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('unit_kind', sa.Enum('POSITIONAL', 'QUANTITY', name='portionunitkind'), nullable=False),
    sa.Column('total_portions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('khatm_id')
    )
    op.create_table('khatm_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_khatm_invitations_khatm_id', 'khatm_invitations', ['khatm_id'], unique=False)
    op.create_table('khatm_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'LEFT', 'REMOVED', name='participationstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participations_khatm_id', 'khatm_participations', ['khatm_id'], unique=False)
    op.create_index('ix_participations_user_id', 'khatm_participations', ['user_id'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('portion_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'BALE', 'SMS', name='notifchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_jobs_khatm_id', 'notification_jobs', ['khatm_id'], unique=False)
    op.create_index('ix_notification_jobs_scheduled_status', 'notification_jobs', ['scheduled_for', 'status'], unique=False)
    op.create_index('ix_notification_jobs_user_status', 'notification_jobs', ['user_id', 'status'], unique=False)
    op.create_table('waiting_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('khatm_id', 'user_id', name='uq_waiting_list_khatm_user')
    )
    op.create_index('ix_waiting_list_khatm_position', 'waiting_list', ['khatm_id', 'position'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CHARGE', 'SPEND', 'REFUND', 'CREDIT', name='txtype'), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_transactions_wallet_id', 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('unit_kind', sa.Enum('POSITIONAL', 'QUANTITY', name='assignmentunitkind'), nullable=False),
    sa.Column('unit_start', sa.Integer(), nullable=True),
    sa.Column('unit_end', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='assignmentstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['khatm_participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_khatm_id', 'assignments', ['khatm_id'], unique=False)
    op.create_index('ix_assignments_participation_id', 'assignments', ['participation_id'], unique=False)
    op.create_index('ix_assignments_status', 'assignments', ['status'], unique=False)
    op.create_table('khatm_portions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('unit_kind', sa.Enum('POSITIONAL', 'QUANTITY', name='portionunitkind'), nullable=False),
    sa.Column('unit_start', sa.Integer(), nullable=True),
    sa.Column('unit_end', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'COMPLETED', name='portionstatus'), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['khatm_participations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['khatm_allocation_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'sequence', name='uq_khatm_portions_plan_sequence')
    )
    op.create_index('ix_khatm_portions_khatm_id', 'khatm_portions', ['khatm_id'], unique=False)
    op.create_index('ix_khatm_portions_participation_id', 'khatm_portions', ['participation_id'], unique=False)
    op.create_index('ix_khatm_portions_plan_id', 'khatm_portions', ['plan_id'], unique=False)
    op.create_index('ix_khatm_portions_status', 'khatm_portions', ['status'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('DAILY_REMINDER', 'FOLLOW_UP', name='notificationkind'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participation_id'], ['khatm_participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_log_participation_sent', 'notification_log', ['participation_id', 'sent_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participation_id'], ['khatm_participations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participation_id')
    )
    op.create_table('open_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khatm_id', sa.UUID(), nullable=False),
    sa.Column('participation_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khatm_id'], ['khatms.id'], ),
    sa.ForeignKeyConstraint(['participation_id'], ['khatm_participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_open_contributions_khatm_id', 'open_contributions', ['khatm_id'], unique=False)
    op.create_index('ix_open_contributions_participation_id', 'open_contributions', ['participation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_open_contributions_participation_id', table_name='open_contributions')
    op.drop_index('ix_open_contributions_khatm_id', table_name='open_contributions')
    op.drop_table('open_contributions')
    op.drop_table('notification_preferences')
    op.drop_index('ix_notification_log_participation_sent', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('ix_khatm_portions_status', table_name='khatm_portions')
    op.drop_index('ix_khatm_portions_plan_id', table_name='khatm_portions')
    op.drop_index('ix_khatm_portions_participation_id', table_name='khatm_portions')
    op.drop_index('ix_khatm_portions_khatm_id', table_name='khatm_portions')
    op.drop_table('khatm_portions')
    op.drop_index('ix_assignments_status', table_name='assignments')
    op.drop_index('ix_assignments_participation_id', table_name='assignments')
    op.drop_index('ix_assignments_khatm_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_wallet_transactions_wallet_id', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('ix_waiting_list_khatm_position', table_name='waiting_list')
    op.drop_table('waiting_list')
    op.drop_index('ix_notification_jobs_user_status', table_name='notification_jobs')
    op.drop_index('ix_notification_jobs_scheduled_status', table_name='notification_jobs')
    op.drop_index('ix_notification_jobs_khatm_id', table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index('ix_participations_user_id', table_name='khatm_participations')
    op.drop_index('ix_participations_khatm_id', table_name='khatm_participations')
    op.drop_table('khatm_participations')
    op.drop_index('ix_khatm_invitations_khatm_id', table_name='khatm_invitations')
    op.drop_table('khatm_invitations')
    op.drop_table('khatm_allocation_plans')
    op.drop_table('wallets')
    op.drop_table('user_settings')
    op.drop_table('user_plans')
    op.drop_index('ix_user_capabilities_user_id', table_name='user_capabilities')
    op.drop_table('user_capabilities')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_platform_identities_user_id', table_name='platform_identities')
    op.drop_table('platform_identities')
    op.drop_index('ix_phone_claims_user_id', table_name='phone_claims')
    op.drop_index('ix_phone_claims_e164', table_name='phone_claims')
    op.drop_table('phone_claims')
    op.drop_index('ix_pending_payments_authority', table_name='pending_payments')
    op.drop_table('pending_payments')
    op.drop_index('ix_otp_challenges_user_e164_purpose', table_name='otp_challenges')
    op.drop_index('ix_otp_challenges_e164', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('ix_khatms_status', table_name='khatms')
    op.drop_index('ix_khatms_creator_user_id', table_name='khatms')
    op.drop_table('khatms')
    op.drop_index('ix_account_merges_winner_user_id', table_name='account_merges')
    op.drop_index('ix_account_merges_loser_user_id', table_name='account_merges')
    op.drop_table('account_merges')
    op.drop_index('ix_users_merged_into_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
